<?php

use VaxLtd\PageBuilderCategoryBlock\Block\Widget;
use Magento\Framework\Escaper;
//use Hyva\Theme\Model\ViewModelRegistry;
//use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Widget $block */
/** @var Escaper $escaper */
///** @var ViewModelRegistry $viewModels */
///** @var HeroiconsOutline $heroicons */

//$heroicons = $viewModels->require(HeroiconsOutline::class);
$items = $block->getItems();
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}
$linkWidgetHtml = $this->helper('VaxLtd\PageBuilderCore\Helper\LinkWidgetHtml');

$title = $block->getTitle();
$subTitle = $block->getSubTitle();
$buttonText = $block->getButtonText();

?>
<?php if ($items): ?>
    <?php foreach ($items as $item): ?>
        <?php var_dump($item); ?>
        <?= isset($item['category']['type']) ? $linkWidgetHtml->getLinkWidgetHtml($item['category']) : '' ?>
    <?php endforeach; ?>
<?php endif; ?>

