<?php

use VaxLtd\PageBuilderContentGrid\Block\Widget\LayoutSecond;
use Magento\Framework\Escaper;
//use Hyva\Theme\Model\ViewModelRegistry;
//use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var LayoutSecond $block */
/** @var Escaper $escaper */
///** @var ViewModelRegistry $viewModels */
///** @var HeroiconsOutline $heroicons */

//$heroicons = $viewModels->require(HeroiconsOutline::class);
$items = $block->getItems();
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}
$linkWidgetHtml = $this->helper('VaxLtd\PageBuilderCore\Helper\LinkWidgetHtml');
$title = $block->getTitle();
$subTitle = $block->getSubTitle();
?>

<?php if ($items): ?>
    <?php foreach ($items as $item): ?>
        <?php var_dump($item); ?>
    <?php endforeach; ?>
<?php endif; ?>


<h1>layout 2</h1>
